// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0pfWWkfACjbPo5-rDeN1ZRF66Z8tTJPw',
    appId: '1:161706194035:web:287ce14527a3b216916606',
    messagingSenderId: '161706194035',
    projectId: 'fir-notification-90b61',
    authDomain: 'fir-notification-90b61.firebaseapp.com',
    storageBucket: 'fir-notification-90b61.appspot.com',
    measurementId: 'G-H5FT6B3MNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEpJ0-TgUv9yxfRGNfG_rNt8t9-W_B-A4',
    appId: '1:161706194035:android:c39ef510f47e9f9d916606',
    messagingSenderId: '161706194035',
    projectId: 'fir-notification-90b61',
    storageBucket: 'fir-notification-90b61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB_bcI6EdAQ2bcw89KA32r5VvLlwF3vSY',
    appId: '1:161706194035:ios:ce4dffc1de974143916606',
    messagingSenderId: '161706194035',
    projectId: 'fir-notification-90b61',
    storageBucket: 'fir-notification-90b61.appspot.com',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB_bcI6EdAQ2bcw89KA32r5VvLlwF3vSY',
    appId: '1:161706194035:ios:6cf4f45311650986916606',
    messagingSenderId: '161706194035',
    projectId: 'fir-notification-90b61',
    storageBucket: 'fir-notification-90b61.appspot.com',
    iosBundleId: 'com.example.firebaseNotification.RunnerTests',
  );
}
